### PR TITLE
Bump ember-cli-babel requirement

### PR DESCRIPTION
**Pull request by travisofthenorth**
Bump ember-cli-babel requirement so that more modern versions of ember can bump the dependency.

### CODE REVIEW

**Comment by travisofthenorth** [comment]
@abuiles I see you're one of the more recent contributors (years ago). Any idea who can approve/merge this?

**Comment by travisofthenorth** [comment]
@adibsaad @ryanlabouve @gilest

**Comment by gilest** [comment]
@jniechcial

**Comment by jniechcial** [comment]
Unfortunately, I don't have permissions for this repository anymore. Perhaps @changs will find someone in Netguru who still has access.

**Comment by gilest** [comment]
@changs tag you're it 🤣

**Comment by travisofthenorth** [comment]
Also, if anyone wants to take a stab after this at getting all the dependencies to latest versions or advise on what that might take, that'd be much appreciated. I want to get babel >= 7 eventually.

**Comment by travisofthenorth** [comment]
Anybody know who still has access to this repo?

**Comment by gilest** [comment]
Help @pharmaceutics @mamut @cintrzyk (Netguru members with ember repos)

**Comment by travisofthenorth** [comment]
Halp! The babel 5 constraint really gets in the way of upgrades (security upgrades in particular).

**Comment by jniechcial** [comment]
I think you have better chances by cloning the repo and applying your fixes there! I have heard that Netguru limited their investment in Ember projects drastically so I don't think there will be traction here.

**Comment by travisofthenorth** [comment]
@jniechcial bummer! Alright I'll go that route for now. Thank you.

**Comment by gilest** [comment]
Another option is https://github.com/adopted-ember-addons

**Pull request closed without merging**
